config:
  prefix: "&7[&3SudoSigns&4-OG&7] "
  console-prefix: "[SudoSigns-OG] "
  currency-symbol-singular: " &BDiamond"
  currency-symbol-plural: " &BDiamonds"
  currency-symbol-in-front: false
  use-decimals-in-prices: false
